# Generated by Django 2.2.9 on 2021-07-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('houseType', models.CharField(max_length=200)),
                ('Elevator', models.CharField(max_length=10)),
                ('renovation', models.CharField(max_length=10)),
                ('typeOfMes', models.CharField(max_length=10)),
                ('userRealName', models.CharField(max_length=40)),
                ('userTel', models.CharField(max_length=30)),
                ('userEmail', models.CharField(max_length=30)),
                ('other', models.CharField(max_length=500)),
                ('userName', models.CharField(max_length=40)),
            ],
        ),
    ]
