# Generated by Django 2.2.9 on 2021-07-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindHouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FindHouseInfo',
        ),
    ]
