# Generated by Django 2.2 on 2021-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=20)),
                ('houseurl', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('huxing', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('chaoxiang', models.CharField(max_length=10)),
                ('zhuangxiu', models.CharField(max_length=10)),
                ('elevator', models.CharField(max_length=5)),
                ('unitPrice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewhouseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=20)),
                ('houseurl', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('huxing', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=10)),
                ('unitPrice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RenthouseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('houseurl', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('huxing', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=10)),
                ('chaoxiang', models.CharField(max_length=10)),
            ],
        ),
    ]
